# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 429baf572c722e2baa72891e42d8dcc58995aca339296b8d777ffe14648b90163200b4cd373f74b18652decf329d480151d46b79fdee1988cf39e4b5a6726c32

test:
  secret_key_base: 7522e5217dea643268b5fd39f8e1dbf51a909ca9836c14359d1be9a2232de075ce3aed111568a8373aa29b20efd678fff2a936ae23ab9fa0f7a7063438aaae15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
